{"uuid": "c3e09ad4-fee0-4cc6-afcc-1bc728388962", "children": ["3bfad90b-7190-497a-9879-d27cf2e109df"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=128.0.6613.115)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6C4DDB5D2+29090]\n\t(No symbol) [0x00007FF6C4D4E689]\n\t(No symbol) [0x00007FF6C4C0B1CA]\n\t(No symbol) [0x00007FF6C4BDFAF5]\n\t(No symbol) [0x00007FF6C4C8E2E7]\n\t(No symbol) [0x00007FF6C4CA5EE1]\n\t(No symbol) [0x00007FF6C4C86493]\n\t(No symbol) [0x00007FF6C4C509B1]\n\t(No symbol) [0x00007FF6C4C51B11]\n\tGetHandleVerifier [0x00007FF6C50F8C5D+3295277]\n\tGetHandleVerifier [0x00007FF6C5144843+3605523]\n\tGetHandleVerifier [0x00007FF6C513A707+3564247]\n\tGetHandleVerifier [0x00007FF6C4E96EB6+797318]\n\t(No symbol) [0x00007FF6C4D5980F]\n\t(No symbol) [0x00007FF6C4D553F4]\n\t(No symbol) [0x00007FF6C4D55580]\n\t(No symbol) [0x00007FF6C4D44A1F]\n\tBaseThreadInitThunk [0x00007FFC2711257D+29]\n\tRtlUserThreadStart [0x00007FFC28A4AF28+40]\n\n", "trace": "  File \"C:\\Users\\manju\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\manju\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\manju\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\manju\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\manju\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\manju\\OneDrive\\Documents\\GitHub\\OrangeHRM_Test_Cases\\test\\conftest.py\", line 36, in setup\n    driver.maximize_window()\n  File \"C:\\Users\\manju\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 506, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\manju\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\manju\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725508358054, "stop": 1725508362784}], "start": 1725508358054, "stop": 1725508363432}